### ISSUE TITLE
The way to merge multi-process point clouds is open to discussion

### ISSUE THREAD

**Issue by XiaomingQu0913** [tiev-tongji/VoxelGridOMP#1]
Here is the part of your code that merges the filtered point clouds of each thread:
```C++
    for (size_t i = 1; i < threads_; ++i) {
        *cloud_all_threads[0] += *cloud_all_threads[i];
    }
//    printf("collect cloud %d from all thread cost: %fms\n", (int)cloud_all_threads[0]->size(), t_col.toc());

    if (final_filter) {
        // Create the filtering object
        pcl::VoxelGrid<PointT> sor;
        sor.setInputCloud(cloud_all_threads[0]);
        sor.setLeafSize(leaf_size_);

        TicToc t_vg;
        sor.filter(output);
        if (console_print)
            printf("final voxel grid PCL cost: %fms\n", t_vg.toc());
    }
    else
        pcl::copyPointCloud(*cloud_all_threads[0], output);
```
It should be a weighted average, rather than simply merging and calling the pcl single-process filter library for filtering.
The benefit of openmp is just to sparse the points collected by each thread. So the running speed is strongly related to the leaf size you set, which is very strange.

**Comment by h-k8888** [comment]
@XiaomingQu0913 
Thanks, you're right. I'll modify it to a weighted form later.
Running speed does strongly correlate with leaf size, that's for sure.

**Comment by XiaomingQu0913** [comment]
Thanks Reply.
Recently I am optimizing the time consumption of lio-sam. I found that as the number of key frames and lidar lines increased, voxel filtering became a time-consuming bottleneck, so I was also considering using openmp to optimize voxel filtering.
Your method does most of the work, and I made a version based on your work. For a 30 million point cloud, the time consumption is reduced from 2.42s to 0.40s. The CPU is i9-12900H, ros-melodic system, and the number of threads is 14.  
Compared to your work, the main change are as follows:
- To avoid false sharing, only after the loop is completed, the "cloud_all_threads" will be changed.
- Merge point clouds using multithreading.  

I will submit a CR to you over the weekend, hope it helps.

**Comment by h-k8888** [comment]
> Thanks Reply. Recently I am optimizing the time consumption of lio-sam. I found that as the number of key frames and lidar lines increased, voxel filtering became a time-consuming bottleneck, so I was also considering using openmp to optimize voxel filtering. Your method does most of the work, and I made a version based on your work. For a 30 million point cloud, the time consumption is reduced from 2.42s to 0.40s. The CPU is i9-12900H, ros-melodic system, and the number of threads is 14. Compared to your work, the main change are as follows:
> 
> * To avoid false sharing, only after the loop is completed, the "cloud_all_threads" will be changed.
> * Merge point clouds using multithreading.
> 
> I will submit a CR to you over the weekend, hope it helps.

I met the same problem in LIO-SAM.
In PCL's Voxel Grid, sorting takes up a huge amount of time. A better idea is to use a Hash table to encode the voxels.
I suggest you check out code in VoxelMap and Faster-LIO.

**Comment by XiaomingQu0913** [comment]
Yes, in my case, sort took up almost half the time.
But for voxel filtering, there seems to be no better solution. I found that filtering using std::unordered_map is nearly twice as slow as sorting.
I have read the papers of faster-lio and voxelmap. For lio-sam, it creates a local map in each key frame, which is very time-consuming. ikdtree or ivox may be able to avoid it. lio-sam performs plane fitting on each iteration, which may also lead to increased time-consuming, voxelmap might be a good plan. I'll try them when I have time later.
Thanks.
